require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe Api::V1::ParksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Park. As you add validations to Park, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {name: 'String',
    description: 'String',
    location: 'String'}
  }

  let(:invalid_attributes) {
    { name: nil,
    description: nil,
    location: nil }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ParksController. Be sure to keep this updated too.
  # let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      park = Park.create! valid_attributes
      get :index, params: {}
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      park = Park.create! valid_attributes
      get :show, params: {id: park.to_param}
      expect(response).to be_success
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {name: 'String2',
        description: 'String2',
        location: 'String2'}
      }

      it "updates the requested park" do
        park = Park.create! valid_attributes
        put :update, params: {id: park.to_param, park: new_attributes}
        park.reload
        expect(response).to be_success
      end

      it "renders a JSON response with the park" do
        park = Park.create! valid_attributes

        put :update, params: {id: park.to_param, park: valid_attributes}
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq('application/json')
      end
    end

    # This one is returning a 200 ok status.
    # context "with invalid params" do
    #   it "renders a JSON response with errors for the park" do
    #     park = Park.create! valid_attributes
    #
    #     put :update, params: {id: park.to_param, park: invalid_attributes}
    #     expect(response).to have_http_status(:unprocessable_entity)
    #     expect(response.content_type).to eq('application/json')
    #   end
    # end
  end

  describe "DELETE #destroy" do
    it "destroys the requested park" do
      park = Park.create! valid_attributes
      expect {
        delete :destroy, params: {id: park.to_param}
      }.to change(Park, :count).by(-1)
    end
  end

end

#Cannot get this one working. It keeps getting the opposite response from expected.
# describe "POST #create" do
  # context "with valid params" do
    # it "creates a new Park" do
    #   expect {
    #     post :create, params: {park: valid_attributes}
    #   }.to change(Park, :count).by(1)
    # end
  #   it "renders a JSON response with the new park" do
  #
  #     post :create, params: {park: valid_attributes}
  #     expect(response).to have_http_status(:created)
  #     expect(response.content_type).to eq('application/json')
  #     expect(response.location).to eq(park_url(Park.last))
  #   end
  # end
  # context "with invalid params" do
  #   it "renders a JSON response with errors for the new park" do
  #
  #     post :create, params: {park: invalid_attributes}
  #     expect(response).to have_http_status(:unprocessable_entity)
  #     expect(response.content_type).to eq('application/json')
  #   end
  # end
# end
